name: test-lint-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: install dependencies
        run: npm install

      - name: run lint
        run: npx lint .

      - name: run test
        run: npx jest
